name: qr_terminal
description: Print QRCodes in your terminal.
version: 1.0.0
homepage: https://github.com/bcattaneo/qr_terminal

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  qr: ^3.0.1
